### PR TITLE
deps: bump up Aplib to latest version

### PR DESCRIPTION
**Pull request by joachimdekker**
This version fixes a few bugs and makes sure the tests run smooth in the pipeline :)

### CODE REVIEW

**Review by Tboefijn — APPROVED** [review]
LGTM!

**Review by SilasPeters — COMMENTED** [review]
Did the XML not change? You should update the XML file as well

**Comment by joachimdekker** [comment]
> Did the XML not change? You should update the XML file as well

@SilasPeters If you mean the XML of the aplib.dll. I have replaced everything in the folder with the newest version. It seems like that XML is the same as the old one.

**Review by SilasPeters — COMMENTED** [review]
*Approves*

**Pull request merged**
